name: english_reading_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  # Core
  mockito: ^5.4.4 # Used to test the app and improve the code quality
  provider: ^6.1.2 # State management library
  dartz: ^0.10.1 # Functional programming library for Dart
  get_it: ^7.7.0 # Service locator for dependency injection
  uuid: ^4.5.0 # Generates unique IDs for objects or entities
  json_annotation: 4.9.0 # Enables code generation for JSON serialization/deserialization
  package_info_plus: ^8.1.0 # Retrieves package information like app version, build number, etc.
  equatable: ^2.0.5 # used to prevent object reference shifts
  internet_connection_checker: ^1.0.0+1 # Checks for active internet connections

  # Config
  easy_localization: ^3.0.7 # Simplifies localization and internationalization of the app
  intl: ^0.19.0 # Provides internationalization and localization facilities

  # Utils
  share_plus: ^10.0.2 # Enables sharing content from the app to other applications
  url_launcher: ^6.3.1 # Launches URLs in a web browser or another app
  change_app_package_name: ^1.4.0 # Allows changing the app package name without manual code adjustments
  image_picker: ^1.1.2 # Enables image picking from gallery or camera
  qr_code_scanner_plus: ^2.0.9+1 # Scans QR codes
  qr_flutter: ^4.0.0 # Generates QR codes
  table_calendar: ^3.0.0

  # Firebase
  firebase_core: ^3.5.0 # Used to initialize and configure Firebase services in the application.
  cloud_firestore: ^5.4.2 # Used for cloud database services.
  firebase_storage: ^12.3.1 # Used for file storage and management.
  

  # Ui
  font_awesome_flutter: ^10.7.0 # Provides Font Awesome icons for Flutter
  cupertino_icons: ^1.0.6 # Cupertino style icons for iOS design
  google_fonts: ^6.2.1 # Allows the use of fonts from Google Fonts
  flutter_speed_dial: ^7.0.0 # Creates floating action buttons with a speed dial effect
  flutter_time_picker_spinner: ^2.0.0 # A time picker spinner for Flutter

  # Cache
  shared_preferences: ^2.3.2 # For local data storage
  hive: ^2.2.3 # A fast and lightweight NoSQL database for local data storage
  hive_flutter: ^1.1.0 # Provides simple and secure data storage with Hive in Flutter applications
  encrypt: ^5.0.3 # Used for data encryption
  flutter_secure_storage: ^9.2.2 # Secure storage for sensitive data (e.g., encrypted data)
  firebase_auth: ^5.4.0
  lottie: ^3.3.1
  google_sign_in: ^6.2.2
  animate_do: ^3.3.4
  shimmer: ^3.0.0
  infinite_scroll_pagination: ^4.1.0
  flutter_tts: ^4.2.3
  google_nav_bar: ^5.0.7
  cached_network_image: ^3.4.1
  flutter_card_swiper: ^7.0.2
  top_snackbar_flutter: ^3.3.0
  image_cropper: ^9.1.0
  dio: ^5.8.0+1
  just_audio: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0 # Code generator for JSON serialization
  build_runner: ^2.3.3 # Build system for Dart to generate code
  very_good_analysis: ^6.0.0 # Linter rules for code quality and consistency
  hive_generator: ^2.0.1 # Generates TypeAdapter code for Hive database

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
    - assets/animations/
