// Mocks generated by Mockito 5.4.5 from annotations
// in english_reading_app/test/add_word/presentation/add_word_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:english_reading_app/core/error/failure.dart' as _i6;
import 'package:english_reading_app/feature/add_word/domain/repository/add_word_repository.dart'
    as _i2;
import 'package:english_reading_app/feature/add_word/domain/usecase/save_word_usecase.dart'
    as _i4;
import 'package:english_reading_app/product/model/dictionary_entry.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAddWordRepository_0 extends _i1.SmartFake
    implements _i2.AddWordRepository {
  _FakeAddWordRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SaveWordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWordUseCase extends _i1.Mock implements _i4.SaveWordUseCase {
  MockSaveWordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AddWordRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeAddWordRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.AddWordRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.DictionaryEntry>> call(
          _i7.DictionaryEntry? word) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [word],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.DictionaryEntry>>.value(
                _FakeEither_1<_i6.Failure, _i7.DictionaryEntry>(
          this,
          Invocation.method(
            #call,
            [word],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.DictionaryEntry>>);
}
