// Mocks generated by Mockito 5.4.5 from annotations
// in english_reading_app/test/saved_articles/domain/usecase/save_article_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i7;
import 'package:dartz/dartz.dart' as _i2;
import 'package:english_reading_app/core/error/failure.dart' as _i5;
import 'package:english_reading_app/feature/saved_articles/domain/repository/saved_articles_repository.dart'
    as _i3;
import 'package:english_reading_app/product/model/article_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SavedArticlesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedArticlesRepository extends _i1.Mock
    implements _i3.SavedArticlesRepository {
  MockSavedArticlesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ArticleModel>>> getSavedArticles({
    int? limit,
    _i7.DocumentSnapshot<Object?>? lastDocument,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedArticles,
          [],
          {
            #limit: limit,
            #lastDocument: lastDocument,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ArticleModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ArticleModel>>(
          this,
          Invocation.method(
            #getSavedArticles,
            [],
            {
              #limit: limit,
              #lastDocument: lastDocument,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ArticleModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveArticle(
          _i6.ArticleModel? article) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveArticle,
          [article],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveArticle,
            [article],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeArticle(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeArticle,
          [articleId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeArticle,
            [articleId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> isArticleSaved(String? articleId) =>
      (super.noSuchMethod(
        Invocation.method(
          #isArticleSaved,
          [articleId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #isArticleSaved,
            [articleId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Set<String>>> getSavedArticleIds() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedArticleIds,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, Set<String>>>.value(
            _FakeEither_0<_i5.Failure, Set<String>>(
          this,
          Invocation.method(
            #getSavedArticleIds,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, Set<String>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ArticleModel>>>
      searchSavedArticles(String? query) => (super.noSuchMethod(
            Invocation.method(
              #searchSavedArticles,
              [query],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.ArticleModel>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ArticleModel>>(
              this,
              Invocation.method(
                #searchSavedArticles,
                [query],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ArticleModel>>>);
}
